# Forçar Railway a ler este arquivo

[phases.setup]
packages = ["python3", "gcc"]

[phases.build]
cmds = ["pip install -r backend/requirements.txt"]

[phases.start]
cmds = ["uvicorn backend.main:app --host=0.0.0.0 --port=$PORT"]

RUN pip show python-jose
