# nixpacks.toml

[phases.setup]
packages = ["python3", "gcc"]

[python]
# instrui o Nixpacks a criar o venv e instalar exatamente deste arquivo
requirements = "backend/requirements.txt"

[phases.start]
cmds = ["uvicorn backend.main:app --host=0.0.0.0 --port=$PORT"]
